package main

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"

	"github.com/anisimov-anthony/vibector/internal/analyzer"
	"github.com/anisimov-anthony/vibector/internal/config"
	"github.com/anisimov-anthony/vibector/internal/detector"
	"github.com/anisimov-anthony/vibector/internal/git"
	"github.com/anisimov-anthony/vibector/internal/metrics"
	"github.com/anisimov-anthony/vibector/internal/reporter"
)

var (
	analyzeOutput              string
	analyzeSuspiciousAdditions int64
	analyzeSuspiciousDeletions int64
	analyzeMaxAdditionsMin     float64
	analyzeMaxDeletionsMin     float64
	analyzeMinTimeDelta        int64
	analyzeBranch              string
	analyzeExcludeFiles        []string
)

var analyzeCmd = &cobra.Command{
	Use:   "analyze <repository>",
	Short: "Analyze repository for suspicious commits",
	Long: `Analyze a git repository to detect commits that may have been generated by AI.

The repository argument should be a local directory path to a git repository

Requires threshold configuration via flags or config file`,
	Args: cobra.ExactArgs(1),
	RunE: runAnalyze,
}

func init() {
	analyzeCmd.Flags().StringVarP(&analyzeOutput, "output", "o", "", "output file path (required, format detected from extension: .txt or .json)")
	_ = analyzeCmd.MarkFlagRequired("output")
	analyzeCmd.Flags().Int64Var(&analyzeSuspiciousAdditions, "suspicious-additions", 0, "flag commits with more than this many additions (0 to disable)")
	analyzeCmd.Flags().Int64Var(&analyzeSuspiciousDeletions, "suspicious-deletions", 0, "flag commits with more than this many deletions (0 to disable)")
	analyzeCmd.Flags().Float64Var(&analyzeMaxAdditionsMin, "max-additions-pm", 0, "max additions per minute (0 to disable)")
	analyzeCmd.Flags().Float64Var(&analyzeMaxDeletionsMin, "max-deletions-pm", 0, "max deletions per minute (0 to disable)")
	analyzeCmd.Flags().Int64Var(&analyzeMinTimeDelta, "min-time-delta", 0, "min seconds between commits (0 to disable)")
	analyzeCmd.Flags().StringVar(&analyzeBranch, "branch", "", "branch to analyze")
	analyzeCmd.Flags().StringSliceVar(&analyzeExcludeFiles, "exclude-files", []string{}, "file patterns to exclude (e.g., *.log,*.tmp)")
}

func runAnalyze(cmd *cobra.Command, args []string) error {
	repoPath := args[0]

	outputFormat, err := detectFormatFromExtension(analyzeOutput)
	if err != nil {
		return err
	}

	cfg, err := config.Load(cfgFile)
	if err != nil {
		return fmt.Errorf("failed to load config: %w", err)
	}

	if cmd.Flags().Changed("suspicious-additions") {
		cfg.Thresholds.SuspiciousAdditions = analyzeSuspiciousAdditions
	}
	if cmd.Flags().Changed("suspicious-deletions") {
		cfg.Thresholds.SuspiciousDeletions = analyzeSuspiciousDeletions
	}
	if cmd.Flags().Changed("max-additions-pm") {
		cfg.Thresholds.MaxAdditionsPerMin = analyzeMaxAdditionsMin
	}
	if cmd.Flags().Changed("max-deletions-pm") {
		cfg.Thresholds.MaxDeletionsPerMin = analyzeMaxDeletionsMin
	}
	if cmd.Flags().Changed("min-time-delta") {
		cfg.Thresholds.MinTimeDeltaSeconds = analyzeMinTimeDelta
	}
	if cmd.Flags().Changed("exclude-files") {
		cfg.ExcludeFiles = analyzeExcludeFiles
	}

	if cfg.Thresholds.IsZero() {
		return fmt.Errorf("no thresholds configured - please set thresholds via config file or flags")
	}

	repoOpts := &git.RepositoryOptions{
		ExcludeFiles: cfg.ExcludeFiles,
	}

	repo, err := git.OpenRepository(repoPath, repoOpts)
	if err != nil {
		return fmt.Errorf("failed to open repository: %w", err)
	}
	defer func() { _ = repo.Close() }()

	a := analyzer.New(repo)
	opts := &git.CommitOptions{
		Branch: analyzeBranch,
	}

	fmt.Fprintln(os.Stderr, "Analyzing repository...")
	result, err := a.AnalyzeRepository(opts)
	if err != nil {
		return fmt.Errorf("analysis failed: %w", err)
	}

	fmt.Fprintln(os.Stderr, "Calculating statistics...")
	stats := metrics.CalculateStats(result.Commits, result.CommitPairs)

	fmt.Fprintln(os.Stderr, "Detecting suspicious commits...")
	det, err := detector.New(&cfg.Thresholds)
	if err != nil {
		return fmt.Errorf("failed to create detector: %w", err)
	}

	suspicious := det.DetectSuspicious(result.CommitPairs, stats)

	rep, err := reporter.NewReporter(outputFormat)
	if err != nil {
		return fmt.Errorf("failed to create reporter: %w", err)
	}

	reportData := &reporter.ReportData{
		Suspicious: suspicious,
		Stats:      stats,
		Thresholds: &cfg.Thresholds,
	}

	reportStr, err := rep.Generate(reportData)
	if err != nil {
		return fmt.Errorf("failed to generate report: %w", err)
	}

	if err := os.WriteFile(analyzeOutput, []byte(reportStr), 0o600); err != nil {
		return fmt.Errorf("failed to write output file: %w", err)
	}
	fmt.Fprintf(os.Stderr, "Report written to %s\n", analyzeOutput)

	return nil
}
